### PR TITLE
Docs: Add example of usafe Mtproto for bots

### PR DESCRIPTION
**Pull request by vb64**

### CODE REVIEW

**Comment by ololosha228** [comment]
Hey @vb64, thanks for contributing!

Unfortunately, i can't accept this PR in current version, but i agree that we must add docs about how exactly you can run telegram bots via this package.

I'll fix asap all problems like a few spell errors, move added files in ./docs, translate to russian, and let you know! Possibly today or tommorow.

**Comment by vb64** [comment]
Насчет русского языка.

Может лучше будет отдельные статьи на русском делать на популярных площадках? Дзен, Хабр и т.п. А ссылки на них собирать в wiki этого проекта. А не городить поддержку для ru в самом проекте?

**Comment by ololosha228** [comment]
@vb64 Sure! If you can contribute via writing posts about how to use this package, it would be soooo amazing!

About russian, i can agree with you, but we have there english speaking people who wants to use this lib and contribute (github is english based, btw). And also, there are so many russian speaking guys who don't understand or too lazy to translate english docs. So, i think that docs localization can help both of them :smile: 

Even though, this not so hard honestly, i personally can speak and write in both languages, so it's not such a big problem to maintain two versions of the docs :+1:

**Comment by quenbyako** [comment]
@vb64 thanks again for contributing, i've personally added your example but just in [another branch](https://github.com/xelaj/mtproto/tree/041af117c512c2531ab1a9a79217990cc40c54ad/examples/auth_bot), so your contributuion is merged, but just in another branch and in modified look, and i hope that it can helps a lot of people!

Thanks a lot!

**Pull request closed without merging**
