### PR TITLE
MTProto 1.0! Now ready to release! 

### PR DESCRIPTION
**Pull request by quenbyako**
This branch contains stable 1.0 release candidate.

Leave here feedback about how does it works!

### CODE REVIEW

**Comment by patrikhermansson** [comment]
Lots of improvements in this one! I'm just hitting one error in what looks like decoding. I can't give much detail but getting this error in the console after running a few minutes, always happens a minute or two after starting, every time i try. I get this error and afterwards I get no more updates so it locks it somehow. Sorry for lack of detail. This is the log:

`&objects.MessageContainer{
  &messages.Encrypted{
    Msg: []uint8{ [REDACTED] },
    MsgID:       [REDACTED],
    AuthKeyHash: []uint8{},
    Salt:        0,
    SessionID:   0,
    SeqNo:       331,
    MsgKey:      []uint8{},
  },
  &messages.Encrypted{
    Msg: []uint8{ [REDACTED] },
    MsgID:       [REDACTED],
    AuthKeyHash: []uint8{},
    Salt:        0,
    SessionID:   0,
    SeqNo:       333,
    MsgKey:      []uint8{},
  },
} nil
nil &errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &errors.withStack{
          error: &errors.withMessage{
            cause: &errors.withStack{
              error: &errors.withMessage{
                cause: &errors.withStack{
                  error: &errors.withMessage{
                    cause: &errors.withStack{
                      error: &errors.withMessage{
                        cause: &errors.withStack{
                          error: &errors.withMessage{
                            cause: &errors.withStack{
                              error: &errors.withMessage{
                                cause: &errors.withStack{
                                  error: &errors.withMessage{
                                    cause: &errors.withStack{
                                      error: &errors.withMessage{
                                        cause: &errors.withStack{
                                          error: &errors.withMessage{
                                            cause: &errors.withStack{
                                              error: &errors.withMessage{
                                                cause: &errors.errorString{
                                                  s: "invalid crc code: 0x7, want: 0xbadcc1a3",
                                                },
                                                msg: "decode field 'Results'",
                                              },
                                              stack: &errors.stack{
                                                0x11e29ca,
                                                0x11e4030,
                                                0x11e35d8,
                                                0x11e28bb,
                                                0x11e4030,
                                                0x11e35d8,
                                                0x11e28bb,
                                                0x11e4030,
                                                0x11e35d8,
                                                0x11e12d8,
                                                0x11e34ca,
                                                0x11e28bb,
                                                0x11e4030,
                                                0x11e22bd,
                                                0x11f50e5,
                                                0x11f59b4,
                                                0x11f8670,
                                                0x106a2a1,
                                              },
                                            },
                                            msg: "decode registered object *telegram.MessageMediaPoll",
                                          },
                                          stack: &errors.stack{
                                            0x11e40ab,
                                            0x11e35d8,
                                            0x11e28bb,
                                            0x11e4030,
                                            0x11e35d8,
                                            0x11e28bb,
                                            0x11e4030,
                                            0x11e35d8,
                                            0x11e12d8,
                                            0x11e34ca,
                                            0x11e28bb,
                                            0x11e4030,
                                            0x11e22bd,
                                            0x11f50e5,
                                            0x11f59b4,
                                            0x11f8670,
                                            0x106a2a1,
                                          },
                                        },
                                        msg: "decode interface",
                                      },
                                      stack: &errors.stack{
                                        0x11e3636,
                                        0x11e28bb,
                                        0x11e4030,
                                        0x11e35d8,
                                        0x11e28bb,
                                        0x11e4030,
                                        0x11e35d8,
                                        0x11e12d8,
                                        0x11e34ca,
                                        0x11e28bb,
                                        0x11e4030,
                                        0x11e22bd,
                                        0x11f50e5,
                                        0x11f59b4,
                                        0x11f8670,
                                        0x106a2a1,
                                      },
                                    },
                                    msg: "decode field 'Media'",
                                  },
                                  stack: &errors.stack{
                                    0x11e29ca,
                                    0x11e4030,
                                    0x11e35d8,
                                    0x11e28bb,
                                    0x11e4030,
                                    0x11e35d8,
                                    0x11e12d8,
                                    0x11e34ca,
                                    0x11e28bb,
                                    0x11e4030,
                                    0x11e22bd,
                                    0x11f50e5,
                                    0x11f59b4,
                                    0x11f8670,
                                    0x106a2a1,
                                  },
                                },
                                msg: "decode registered object *telegram.MessageObj",
                              },
                              stack: &errors.stack{
                                0x11e40ab,
                                0x11e35d8,
                                0x11e28bb,
                                0x11e4030,
                                0x11e35d8,
                                0x11e12d8,
                                0x11e34ca,
                                0x11e28bb,
                                0x11e4030,
                                0x11e22bd,
                                0x11f50e5,
                                0x11f59b4,
                                0x11f8670,
                                0x106a2a1,
                              },
                            },
                            msg: "decode interface",
                          },
                          stack: &errors.stack{
                            0x11e3636,
                            0x11e28bb,
                            0x11e4030,
                            0x11e35d8,
                            0x11e12d8,
                            0x11e34ca,
                            0x11e28bb,
                            0x11e4030,
                            0x11e22bd,
                            0x11f50e5,
                            0x11f59b4,
                            0x11f8670,
                            0x106a2a1,
                          },
                        },
                        msg: "decode field 'Message'",
                      },
                      stack: &errors.stack{
                        0x11e29ca,
                        0x11e4030,
                        0x11e35d8,
                        0x11e12d8,
                        0x11e34ca,
                        0x11e28bb,
                        0x11e4030,
                        0x11e22bd,
                        0x11f50e5,
                        0x11f59b4,
                        0x11f8670,
                        0x106a2a1,
                      },
                    },
                    msg: "decode registered object *telegram.UpdateNewChannelMessage",
                  },
                  stack: &errors.stack{
                    0x11e40ab,
                    0x11e35d8,
                    0x11e12d8,
                    0x11e34ca,
                    0x11e28bb,
                    0x11e4030,
                    0x11e22bd,
                    0x11f50e5,
                    0x11f59b4,
                    0x11f8670,
                    0x106a2a1,
                  },
                },
                msg: "decode interface",
              },
              stack: &errors.stack{
                0x11e3636,
                0x11e12d8,
                0x11e34ca,
                0x11e28bb,
                0x11e4030,
                0x11e22bd,
                0x11f50e5,
                0x11f59b4,
                0x11f8670,
                0x106a2a1,
              },
            },
            msg: "decode field 'Updates'",
          },
          stack: &errors.stack{
            0x11e29ca,
            0x11e4030,
            0x11e22bd,
            0x11f50e5,
            0x11f59b4,
            0x11f8670,
            0x106a2a1,
          },
        },
        msg: "decode registered object *telegram.UpdatesObj",
      },
      stack: &errors.stack{
        0x11e40ab,
        0x11e22bd,
        0x11f50e5,
        0x11f59b4,
        0x11f8670,
        0x106a2a1,
      },
    },
    msg: "decoding predicted object",
  },
  stack: &errors.stack{
    0x11e22fc,
    0x11f50e5,
    0x11f59b4,
    0x11f8670,
    0x106a2a1,
  },
}`

**Comment by ololosha228** [comment]
@patrikhermansson looks like tl decoder has a few problems, can you dig binary message and post here with expected result? or create new issue

**Comment by patrikhermansson** [comment]
Sounds like it. I can't share it here unfortunately but happy to email you.

**Comment by ololosha228** [comment]
@patrikhermansson sure, mail me at rcooper.xelaj@pm.me or in telegram [@zhopakotabot](https://t.me/zhopakotabot)

**Comment by airani** [comment]
@ololosha228 When do you think v1.0 will be released?

**Comment by ololosha228** [comment]
@airani it'll be released when we collect a sufficiently large number of feedback, cause we want to provide at most stable library as it possible (even if telegram api isn't stable)

**Comment by lonesta** [comment]
panic: processing response: unmarshaling response: decoding predicted object: decode registered object *objects.RpcResult: decode field 'Obj': decode interface: parsing gzipped object: decoding predicted object: decode registered object *telegram.MessagesChannelMessages: decode field 'Messages': decode interface: decode registered object *telegram.MessageObj: decode field 'Media': decode interface: decode registered object *telegram.MessageMediaPoll: decode field 'Results': invalid crc code: 0x4, want: 0xbadcc1a3


when i use MessagesGetHistory

**Comment by quenbyako** [comment]
@lonesta thanks for responding! Could you please append here original binary message? Cause it can really help to inspect what happened here and how to fix

If you have really sensitive data, please, don't post here, instead, write me at telegram [@zhopakotabot](t.me/zhopakotabot)

**Comment by quenbyako** [comment]
To notify guys who hates `go-dry` package, we decided to rework it, see #57 note

**Pull request merged**
