### PR TITLE
Replace github.com/pkg/errors with stdlib errors wrapping

### PR DESCRIPTION
**Pull request by xakep666**

### CODE REVIEW

**Comment by ololosha228** [comment]
Hey @xakep666, thanks for contributing!

First of all, i agree with one of your changes: we shoud use fmt instead strconv for looking more readable.

But, unfortunately, i need to reject this PR for main reason:
`fmt.Errorf() != errors.Wrap()`. stdlib formatted error creates simplest error as inherited string, but errors.Wrap create container which contains wrapped error instead. This is way more useful, than simple string.

Check out [this post](https://blog.golang.org/go1.13-errors) and its [russian translation](https://habr.com/ru/company/mailru/blog/473658/) how to deal with errors in modern go1.13+.

Also, check out [this guide](https://banzaicloud.com/blog/error-handling-go/), which is explain, why `pkg/errors` is still way more better than stdlib `errors` package.

Even though, i don't want to close your PR, cause you done good thing: converting strconv cases to fmt, whis we wanted to do. I really appreciate your job.

**Comment by xakep666** [comment]
Actually `fmt.Errorf` with `%w` also creates error container carrying initial error (https://golang.org/src/fmt/errors.go?s=624:674#L7). You can use `errors.Is` (for error-values) or `errors.As` (for error-types) so it's possible to find a root cause.
Also I've read provided articles and in second one stdlib errors are not mentioned.

And I think it's better to get rid of dependencies where stdlib packages can be used.

**Comment by ololosha228** [comment]
@xakep666 can you create 2 PRs, please? Cause i can't split your commits between single PR.

First one with strconv to fmt, we will merge it asap, second one with pkg errors to stdlib, cause our team is torning between changing pk errors and not changing.

**Comment by xakep666** [comment]
@ololosha228 Do I correctly understand that I need to replace `strconv` with `fmt` inside `errors.Wrap`?

**Comment by xakep666** [comment]
@ololosha228 do you have any considerations about replacing pkg/errors with stdlib errors at this moment? Should this PR be closed or updated with resolved conflicts?

**Comment by ololosha228** [comment]
Must close this PR, cause our team decided to save this dependency for future improvements. We will try to come back to this question after few months, if we collect multiple requests for leaving this dep.

**Pull request closed without merging**
